import type { Metadata } from "next";
import { GeistSans } from 'geist/font';
import { GeistMono } from 'geist/font';
import "./globals.css";
import Link from "next/link";
import Navbar from "./Navbar";
import Image from 'next/image';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        <title>IMI ARTS | Where Design Meets Perfection | Offset Printing & Web Development in India</title>
        <meta name="description" content="IMI ARTS offers premium offset printing, website development, visual aid books, multicolor labels, and medical carton box services for doctors, pharmaceutical companies, businesses, and startups across India. Elevate your brand with our expert solutions." />
        <meta name="keywords" content="IMI ARTS, offset printing, web development, visual aid books, multicolor labels, medical carton box, Chennai, India, printing for doctors, pharma printing, business printing, startup web development" />
        <meta property="og:title" content="IMI ARTS | Where Design Meets Perfection" />
        <meta property="og:description" content="Premium offset printing and web development for doctors, pharma, businesses, and startups across India." />
        <meta property="og:image" content="/images/IMIlogo.png" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://imiarts.com" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="IMI ARTS | Where Design Meets Perfection" />
        <meta name="twitter:description" content="Premium offset printing and web development for doctors, pharma, businesses, and startups across India." />
        <meta name="twitter:image" content="/images/IMIlogo.png" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700;900&display=swap" rel="stylesheet" />
      </head>
      <body className={GeistSans.className} style={{ fontFamily: 'Nunito, Arial, sans-serif' }}>
        {/* Navbar */}
        <Navbar />
        <main className="flex-1 w-full">
          {children}
        </main>
        {/* Footer */}
        <footer className="w-full bg-[#34486b] text-white py-8 px-6 mt-12">
          <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between gap-8">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Image
                  src="/images/IMIlogo.png"
                  alt="IMI ARTS Logo"
                  width={150}
                  height={50}
                  className="h-12 w-auto"
                />
                <span className="font-bold text-lg">IMI ARTS</span>
              </div>
              <p className="text-sm">Where Design Meets Perfection</p>
              <p className="text-xs mt-2">13, 57 street, 10 sector, Ayyavupuram, K. K. Nagar, Chennai, Tamil Nadu 600078</p>
              <p className="text-xs">Phone: +91 9444218037</p>
              <p className="text-xs">Email: imi_arts@yahoo.com</p>
            </div>
            <div>
              <h4 className="font-semibold mb-2">Useful Links</h4>
              <ul className="text-sm space-y-1">
                <li><Link href="/">Home</Link></li>
                <li><Link href="#services">Services</Link></li>
                <li><Link href="/projects">Projects</Link></li>
                <li><Link href="#contact">Contact</Link></li>
                <li><Link href="/admin">Admin</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-2">Our Services</h4>
              <ul className="text-sm space-y-1">
                <li>Offset Printing</li>
                <li>Website Development</li>
                <li>Visual Aid Books</li>
                <li>Multicolor Labels</li>
                <li>Medical Carton Box</li>
              </ul>
            </div>
          </div>
          <div className="text-center text-xs text-gray-300 mt-8">© {new Date().getFullYear()} IMI ARTS. All rights reserved.</div>
        </footer>
      </body>
    </html>
  );
}
